<h3>1.	Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1000 and 2000 (both included).</h3>

In [2]:
for i in range(1000,2000):
    if (i%7==0 and i%5==0):
        print(i,end=" ")


1015 1050 1085 1120 1155 1190 1225 1260 1295 1330 1365 1400 1435 1470 1505 1540 1575 1610 1645 1680 1715 1750 1785 1820 1855 1890 1925 1960 1995 

In [6]:
a= input("would you like to convert celcius or fahrenheit")
if (a=="celsius"):
    c= int(input("waht is the temp in celsius?"))
    f= (9*c/5)+32
    print(f"the temp in fahrenheit is {f}")
else:
    f= int(input("waht is the temp in fahrenheit?"))
    c=(f-32)/9*5
    print(f"the temp in celcius is {c}")


ValueError: invalid literal for int() with base 10: ''

In [1]:
import random

while True:
    c=input("Please guess the number between 1 to 9")
    d=int(c)
    b=random.randint(1,9)
    if (d==b):
        print("successful guess")

    else:
        print("You are dumb")

ValueError: invalid literal for int() with base 10: ''

In [21]:
a=5
b="*"
c=0
d=[]
for i in range(1,10):
    
    for j in range(i-c):
        if i>=(5):
            c+=1  

        print(b, end='')
        
    print("")

*
**
***
****
*****
*
*
*
*


In [22]:
#print("good day")
take_date = input("Enter a date in dd-mm-yyyy format")
if len(take_date)==10 and take_date[2]=="-" and take_date[5]=="-" and int(take_date[:2])<=31 and int(take_date[3:5])<=12:
    
    if int(take_date[-4:]) %4 ==0 and int(take_date[3:5])==2 and int(take_date[:2])==29:
        new_date="01-"+"03-"+take_date[-4:]
        print(new_date)
    else:
        if (int(take_date[3:5])<=12 and int(take_date[3:5])%2 !=0): # odd months
            if (int(take_date[:2])==31): #change of months 

                month = int(take_date[3:5]) 
                year = take_date[6:10] 
                month = month + 1 if month < 12 else 1
                month_str = str(month).zfill(2)
                new_date = "01-" + month_str + "-" + year 
                
                print("the next date is "+new_date)
            else: # change of only days
                new_day=int(take_date[:2])+1
                day_str=str(new_day).zfill(2)
                new_date=day_str+take_date[2:10]
                print("the next date is "+new_date)
        else:
            if (int(take_date[:2])==30): #change of months 

                month = int(take_date[3:5]) 
                year = take_date[6:10] 
                month = month + 1 if month < 12 else 1
                month_str = str(month).zfill(2)
                new_date = "01-" + month_str + "-" + year 
                
                print("the next date is "+new_date)
            else: # change of only days
                new_day=int(take_date[:2])+1
                day_str=str(new_day).zfill(2)
                new_date=day_str+take_date[2:10]
                print("the next date is "+new_date)

else:
    print("wrong format")
    


the next date is 32-04-2019


In [11]:
a="shrestharonak"
a[-4:]

'onak'

In [23]:

def next_day(take_date):
    check_return=check_date_validity(take_date)
    if check_return =="add_normal_day":
        new_date=add_next_day("add_normal_day",take_date)
    
    elif check_return=="end_month_feb":
        new_date=add_next_day("end_month_feb",take_date)

    elif check_return=="end_month_even":
        new_date=add_next_day("end_month_even",take_date)

    elif check_return=="end_month_odd":
        new_date=add_next_day("end_month_odd",take_date)
    elif check_return=="end_year":
        new_date=add_next_day("end_year",take_date)
    else:
        print(check_return)
    print("the next date is "+new_date)

def check_date_validity(take_date):
    if len(take_date)==10 and take_date[2]=="-" and take_date[5]=="-"  and int(take_date[3:5])<=12  and int(take_date[:1])<=31 and int(take_date[3:5]) >= 0 and int(take_date[:1]) >= 0 :#check date format
        if int(take_date[-4:])%4 ==0:
            leap_year=True
        if int(take_date[3:5]) ==2 and int(take_date[:1])<=29:
            if int(take_date[:1])==29 and leap_year is False:
                return ("wrong date format for februery. is not leap year")
            else:
                if int(take_date[:1])==29 and leap_year is True:
                    return "end_month_feb"
                else: 
                    return "add_normal_day" 
        
        elif int(take_date[3:5]) ==12 and int(take_date[:1])<=31:
            return "end_year"
            
        elif int(take_date[3:5])%2==0 and int(take_date[:1])<=30 :
            if int(take_date[:1]==30):
                return "end_month_even"
            else:
                return "add_normal_day"
        elif int(take_date[3:5])%2!=0 and int(take_date[:1])<=31 :
            if int(take_date[:1]==30):
                return "end_month_odd"
            else:
                return "add_normal_day"
    else:
        return "provided date in wrong format"

def add_next_day(status,take_date):
    if status=="add_normal_day":
        new_day=int(take_date[:2])+1
        day_str=str(new_day).zfill(2)
        new_date=day_str+take_date[2:10]
        return new_date
    
    elif status=="end_year":
        new_year=int(take_date[-4:])+1
        str_year=str(new_year)
        new_date= "01-"+"01-"+str_year
        return new_date
    else:
        month = int(take_date[3:5]) 
        year = take_date[6:10] 
        month = month + 1 if month < 12 else 1
        month_str = str(month).zfill(2)
        new_date = "01-" + month_str + "-" + year 
        return new_date

next_day(take_date = input("Enter a date in dd-mm-yyyy format"))



the next date is 01-01-2022


In [2]:
for i in range (1,11):
    print(f"4*{i}={4*i}")

4*1=4
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
4*10=40


<h1>Week 4- Workshop</h1>

In [2]:
import numpy as np
#1.	Element-wise addition of 2 numpy arrays
a =np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [4]:
#2.	Multiply Matrix by a scalar.
a =np.array([1,2,3,4])
b=a*5
b

array([ 5, 10, 15, 20])

In [15]:
#3.	Create an Identity matrix.
identity_matrix=np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#4.	Convert 1D array to 3D array.
a=np.array([1,2,3,4,5,6,7,8,9])
a.reshape(3,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [24]:
#5.	Write a python code to convert data type from float to integer.
a=np.array([1,2,3,4,5,6,7,8,9],dtype=float)
b=a.astype(int)
b.dtype

dtype('int32')

In [25]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 5, 7, 4, 9])

matching_positions = np.where(array1 == array2)

print(matching_positions)

(array([3], dtype=int64),)


In [29]:
#7.	Matrix Generation with one particular value
a=np.ones(5)*5
a

array([5., 5., 5., 5., 5.])

In [33]:
#8.	Replace all odd numbers in the given array with -1
a=np.arange(0,5)
for i in range(len(a)):
    if a[i] % 2 !=0:
        a[i]=-1
a


array([ 0, -1,  2, -1,  4])

In [35]:
#9.	Get the positions where elements of a and b match
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

matching_positions = np.where(a == b)
matching_positions


(array([1, 3, 5, 7], dtype=int64),)