In [2]:
#import packages
import numpy as np

In [3]:
#1
myList= [x**2 for x in range(5)]
myArray=np.array(myList)
myArray

array([ 0,  1,  4,  9, 16])

In [4]:
print(myArray.ndim)
print(myArray.shape)
print(len(myArray))
print(myArray.dtype)

1
(5,)
5
int32


# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [5]:
my_one= np.ones((5,2),dtype=np.int8)


In [6]:
random_array= np.random.rand(3,3)
random_array

array([[0.32963464, 0.04599771, 0.67138461],
       [0.76362948, 0.48693547, 0.67089558],
       [0.59815687, 0.9005043 , 0.2424056 ]])

In [7]:
#slicing
random_array[:2]

array([[0.32963464, 0.04599771, 0.67138461],
       [0.76362948, 0.48693547, 0.67089558]])

In [8]:
random_array[:,:1]

array([[0.32963464],
       [0.76362948],
       [0.59815687]])

In [9]:
# 2nd element third row
random_array[2:3,1:2]
random_array[2][1]

0.9005042989237324

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [10]:
#1
product=np.array(['Cola','fanta','pickle','lags','cake','sprint'])
prices=np.array([20,1230,800,190,12,400])
prices_after_shipping=prices+5
print(prices_after_shipping)
#2
discount_pct=random_array.flatten()[:6]
print(discount_pct)

#3
pct_owned=1-discount_pct
print(pct_owned)

print("the price after discount is:")
final_price=prices_after_shipping*pct_owned
print(final_price)


[  25 1235  805  195   17  405]
[0.32963464 0.04599771 0.67138461 0.76362948 0.48693547 0.67089558]
[0.67036536 0.95400229 0.32861539 0.23637052 0.51306453 0.32910442]
the price after discount is:
[  16.75913402 1178.19282704  264.53538553   46.0922513     8.72209708
  133.28728948]


# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [11]:
bool_1=(prices>25) |(product=="Cola")

fancy_feast=product[bool_1]
fancy_feast

shipping_cost=np.where(prices>20, 0, 5)
new_price_array=final_price+shipping_cost



In [12]:
top_three_items=np.sort(new_price_array)[::-1][:3]
top_three_items

array([1178.19282704,  264.53538553,  133.28728948])

In [13]:
a=[1,2,3,4,5,6,7,8]
a[-5:7]

[4, 5, 6, 7]

In [14]:
np.median(new_price_array)

89.68977038927568

In [15]:
from collections import  Counter

bin= [0,50,100,500,1000, np.inf]

price_range=np.digitize(final_price, bin)

unique_count=Counter(zip( price_range,final_price))

for i in range(1,len(bin)):
    range_name= f'[{bin[i-1], bin[i]}]'
    count= sum(1 for key in unique_count if key[0]==1)
    print(f"Number of unique prices in range {range_name}: {count}")

Number of unique prices in range [(0, 50)]: 3
Number of unique prices in range [(50, 100)]: 3
Number of unique prices in range [(100, 500)]: 3
Number of unique prices in range [(500, 1000)]: 3
Number of unique prices in range [(1000, inf)]: 3


<h1>Pandas</h1>

In [16]:
data_labels_1=['apple','banana','grapes','pineapple','mango']
data_values_1=[40,50,60,30,70]
series_nummy_serpy_array_1=np.array(data_labels_1)
dict2= dict(zip(data_labels_1,data_values_1))
dict2

{'apple': 40, 'banana': 50, 'grapes': 60, 'pineapple': 30, 'mango': 70}

In [17]:
import pandas as pd
indexes = ['Biratnagar', 'Kathmandu', 'Lalitpur', 'Pokhara', 'Narayangarh']
data = [200000, 1600000, 600000, 500000, 350000]

cities_population=pd.Series(data, index=indexes)
cities_population

Biratnagar      200000
Kathmandu      1600000
Lalitpur        600000
Pokhara         500000
Narayangarh     350000
dtype: int64

In [18]:
cities_population.index

Index(['Biratnagar', 'Kathmandu', 'Lalitpur', 'Pokhara', 'Narayangarh'], dtype='object')

In [19]:
indexes = ['Bhaktapur', 'Kathmandu', 'Lalitpur', 'Pokhara', 'Butwal']
data = [150000, 1600000, 600000, 500000, 300000]

cities_population_2= pd.Series(data, index= indexes)

cities_population+cities_population_2

Bhaktapur            NaN
Biratnagar           NaN
Butwal               NaN
Kathmandu      3200000.0
Lalitpur       1200000.0
Narayangarh          NaN
Pokhara        1000000.0
dtype: float64

In [20]:
serial_no= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] #row indexes
subjects =['ENG', 'NEP', 'MAT', 'SCI', 'COM'] #column headers
students =['RAM','SHYAM','GITA','HARI','SITA','SUSHILA','RAMESH','SUBODH','ANIL','RUPA']
marks =[[57, 34, 93, 84, 54], [48, 49, 52, 89, 64], [66, 64, 75, 38, 84], [55, 47, 90, 82, 37], [45, 93, 70, 53, 76], [45, 63, 33, 53, 72], [68, 34, 42, 43, 84], [62, 69, 67, 50, 94], [59, 33, 51, 68, 33], [57, 91, 60, 37, 44]]

df_=pd.DataFrame(marks, index=serial_no, columns= subjects)
df_.index.name='Serial No'
df_.columns.name='Subject'

df_['Student']=students

desired_columns = ['Student'] + subjects  # List of columns in desired order
df_ = df_[desired_columns]  # Reorder DataFrame columns
df_

Subject    Student  ENG  NEP  MAT  SCI  COM
Serial No                                  
1              RAM   57   34   93   84   54
2            SHYAM   48   49   52   89   64
3             GITA   66   64   75   38   84
4             HARI   55   47   90   82   37
5             SITA   45   93   70   53   76
6          SUSHILA   45   63   33   53   72
7           RAMESH   68   34   42   43   84
8           SUBODH   62   69   67   50   94
9             ANIL   59   33   51   68   33
10            RUPA   57   91   60   37   44

In [24]:
df_[df_['NEP']>40]['Student']

Serial No
2       SHYAM
3        GITA
4        HARI
5        SITA
6     SUSHILA
8      SUBODH
10       RUPA
Name: Student, dtype: object

In [25]:
df_[df_['SCI']>70]['Student']

Serial No
1      RAM
2    SHYAM
4     HARI
Name: Student, dtype: object

In [29]:
salary_path=r"C:\Users\hp\Downloads\Salaries.csv"
df= pd.read_csv(salary_path)
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [35]:
print(pd.DataFrame.mean(df['BasePay']))
print(df['BasePay'].mean())

66325.4488404877
66325.4488404877


In [37]:
df['OvertimePay'].max()

245131.88

In [38]:
df[df['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [39]:
df[df['EmployeeName']=='JOSEPH DRISCOLL'][['JobTitle']]

JobTitle
24  CAPTAIN, FIRE SUPPRESSION

In [40]:
df[df['EmployeeName']=='JOSEPH DRISCOLL'][['TotalPayBenefits']]

TotalPayBenefits
24         270324.91

In [46]:
df[df['TotalPayBenefits']==df['TotalPayBenefits'].max()][['EmployeeName','TotalPayBenefits']]

EmployeeName  TotalPayBenefits
0  NATHANIEL FORD         567595.43

In [49]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].min()][['EmployeeName','TotalPayBenefits','TotalPay','Benefits']]

EmployeeName  TotalPayBenefits  TotalPay  Benefits
148653    Joe Lopez           -618.13   -618.13       0.0

In [62]:
my_group=df.groupby(['Year'])[['BasePay']].mean()

my_group

BasePay
Year              
2011  63595.956517
2012  65436.406857
2013  69630.030216
2014  66564.421924

In [64]:
b=df['JobTitle'].nunique()
b

2159

In [72]:
job_title_counts = df['JobTitle'].value_counts()
job_title_counts.head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [75]:
job_title_counts = df.groupby('JobTitle').size()

job_title_counts_df = job_title_counts.reset_index(name='Count')

sorted_job_title_counts_df = job_title_counts_df.sort_values(by='Count', ascending=True)

tail_sorted_job_title_counts_df = sorted_job_title_counts_df.tail()
print(tail_sorted_job_title_counts_df)

                          JobTitle  Count
1482              Police Officer 3   2421
1544  Public Svc Aide-Public Works   2518
1577              Registered Nurse   3736
1902                 Special Nurse   4389
2056              Transit Operator   7036


In [77]:
sum(df[df['Year']==2013]['JobTitle'].value_counts()==1)

202

In [81]:
sum(df['JobTitle'].str.lower().str.contains('chief'))

627

In [82]:
df['len_jobT']=df['JobTitle'].apply(len)

In [93]:
c_df=['len_jobT','TotalPayBenefits']

df[c_df].corr()

len_jobT  TotalPayBenefits
len_jobT          1.000000         -0.036878
TotalPayBenefits -0.036878          1.000000